travis:
  secure:
    BINSTAR_TOKEN: SVDRyLE9MvgQKiv77v8wC99lBc3CLC5K+CJD5sBrpcARlhNm3OaiMkrbxXWEF8dF+1ZwzG+oJy1PY7KwEsMIzZ8m/QcdeulTzPLWJsERFvASMwatg6YZncLuhDsqBn8N6gIsQPTXy+UP13en/tAWPqtIX3aw1sUmrT6vFl5LB4VCJZMF19ANLfSZIKG3qmRhrpG8Qqm9LPtdRNxmo2xmrsdveHUGMg0GIEJ46ITYfte3sEkutGcCiSkIvScLgKuHkgIpFgPScWFX/gHav/6sTcb2d8BD9wnbI3i5VXO2JuCgjkGHqLnUcKfNY13fLnqu5m4STh+e4fGmxpeGhGvJAd+1+f9ViCExjoaEVlqlGYoLCjdYu8v4Gy2pJjEclljIpNSt6C1l85A+QCdXlv7apqFZDL05o/L9lCat9/xp+j4Ld3olw4qmG7MzdYBHEJzu3FkNgngCExedM8rvLp3QWkc7H1/LXRYWM/I0fnSYJp7in4mXq4WD+fzjigLKUKrvstcHu4WWuBj6KpWXeXOPNRdr5Fw4QASDtUnulaHJZV01HtVo+OmwuiGzKMYkh3/2+YkYfhbK4Iep/aHLSkXT/bxoepl6JumRNLQh5GkirJaM2KKzPtQFgq/E0wQWmg+PDgn9JPbWs6SHAni10CXXgYRUM3ZADufCIX/BRxSMi+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
