travis:
  secure:
    BINSTAR_TOKEN: DTjuhKcq2roV1GMv+eZkWDdHRrL2APtcuMJw/ZDgjNXJNRyH20QIPMjQ738/7i4zhg4iP3ocY000G0MITDAAOhrPV8lU29SMygi5rDOc674WVkDBC4WU7XGxV/JVDFNJMdeVhFfv8V1HSakK3DOZIkFd3/3JukIK7D7T60UY86Ii3lg2t8xY0tBN5SRt7oHroEp7FaihDSLcZlSlvFUqXB+/FvFD/rpPiO7242Mw6lg3S6a3u+OUro1CBO9Zihx/sxCIREcIreyJzugC9UVIYLdbF4S81EaBPTnhrm/XvPPiE+yUs7DcB3C57y20q17h4TPCITWh9Bsp15CaaWHkwcG1Mh4lHGtix/EebYm9jNsGfA1ATyJcYY3BmM5Haj3tJJ0ELgTjHPGG2llaBmiF1w2n5T2Qq5OakuySHKxBZtarYSim6IAiP3eHh4y0jx+3Oi7xDKYidnN+L6rYmtbnt6X9In+UwXa2q0SkBFwrQ3dHo8+Bq1LQeUKHhsaCad2yiMShHjJ+Np2fkysbt3yNoDRiy1DhRU3G8UENON6cwT+d7kLRj+jMReKG/du2c5Hjxiamw7NnCb9ixCoX3eXeC+Cs82RxM2Nq1/cRvPf7O0Q2zDWOnfrK8luozalOqjm6Bs8iJJpznTa8YPfsXFvHml6EAAjaKOqnbsMB1vvYo/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
